name: Deploy PR previews

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        if: github.event.action != 'closed'
        uses: pnpm/action-setup@v4

      - name: Install node
        if: github.event.action != 'closed'
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install and Build
        if: github.event.action != 'closed' # We don't need the build if we know the preview will be removed
        run: |
          pnpm install --frozen-lockfile
          pnpm generate

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./.output/public
          preview-branch: gh-pages
          qr-code: true
